name: ğŸ¤– Welcome PR Commenter

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add Welcome Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ğŸ‘‹ Hi @${{ github.actor }}!  

            ğŸ‰ **Thank you for your Pull Request and for contributing to this project!**  

            Please make sure you've followed all the required rules before we review your PR:
            1ï¸âƒ£ No DSA codes  
            2ï¸âƒ£ Contributed in allowed categories. 
            3ï¸âƒ£ Added snapshots or a deployed link (Only if you are adding new project) 
            4ï¸âƒ£ Followed [Shubham](https://github.com/shubham7668) and â­ starred the repo  

            âš ï¸ *Non-working or spam PRs will be marked invalid and may disqualify you from Hacktoberfest.*  

            Once ready, a maintainer will review your PR soon. ğŸš€  

            â€” *Automated message from the PowerShell Showcase Bot*
